### ISSUE TITLE
'user' is only accepted with lower case

### ISSUE THREAD

**Issue by thomashafner** [Daimler/sechub#296]
Both in the JSON config file as well as via command line the 'user' is only accepted with lower case. Please fix this.

**Comment by de-jcup** [comment]
## Why sechub allows only lowercase
Hmm.. sechub does only accept usernames in lowercase. 

Why ? The reason is, to avoid situations were users register themselves with differnt user Ids, but user ids only differ in case... It would be terrible to administrate when you are talking about a user id but effectively there would be multiple users which could be meant.

So only accepting lower cased characters was the easiest way to achive this. 

## Solution
But when it's very inconvient for you - e.g. when you are using a system user name or a company account which is always upper cased and your are using the information for scripting etc. , we could do following inside the client:

After user id has bean read (either environment entry, parameter or from config file) we could always transform automatically to lowercase inside SecHub client. 

So this will solve the problem for you and we do not change server logic.

## Implementation details

- [ ] automatically lowercase user id inside client context structure after read
- [ ] update documentation about the automatic transformation to lowercase
- [ ] client should log/output the information about transforming name to lowercase so its clear on caller side what was happening

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>
