### ISSUE TITLE
Change go client, so apitoken can be set by environment entry instead argument

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#36]
Currently we got same situation for go client as for admin ui, see #8 :
Everybody able to see processes on server side does also see api token used by calling
sechub client.

**SECHUB_APITOKEN** environment shall be an addition to existing code. It shall be downward compatible. But a warning should be printed out when user is using argument instead of env entry.

**Comment by de-jcup** [comment]
Obsolute, because somebody having access to process list of another user has normally admin rights. Having admin rights you can do - at least on linux:

`sudo cat /proc/$PID/environ `

should be possible at windows as well, so makes no difference.

**Comment by de-jcup** [comment]
Andreas thank you ! You are absolutely right... will reopen issue and integrate into next release.

**Comment by sven-dmlr** [comment]
Created branch feature-36-api-token-as-env-variable

- added possibilty to pass SecHub api token as environment variable SECHUB_APITOKEN
- Additionally added a warning message when using -apitoken instead of the environment variable.
- added possibilty to pass SecHub UserID as environment variable SECHUB_USERID
- added possibilty to pass SecHub Server String as environment variable SECHUB_SERVER
