### ISSUE TITLE
HTML Report: Id ambigious

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#576]
At the moment, the call number is named `Id` instead of `Call` in the HTML report. This is confusing, because the JSON report has an `Id` field. One can mistake the `Id` in the HTML report as the Id in the JSON report. In addition, the call stack should start with 1 and not 0.

![Screenshot at 2021-03-04 13-00-44](https://user-images.githubusercontent.com/2007739/109993370-82a71680-7d0c-11eb-90c8-50b57f0489bf.png)

The solution is to:

1. Introduce a new Id column, which shows the `Id` from the JSON file
2. Rename the `Id` in the call stack to `Call` or `Call Number`
3. Start counting the calls from the callstack at 1

![call_stack_should_be](https://user-images.githubusercontent.com/2007739/109993299-6efbb000-7d0c-11eb-91f6-96555d5ebe1f.png)

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by company-jcup** [comment]
This is a **critical** problem, because Users could use the wrong number for the false-positive markers! 
We should implement this very soon!

**Comment by de-jcup** [comment]
Inside the HTML report "Id" is not the finding ids but the call step number (even this was the wrong one, because steps also start with 1 here).

Unfortunately this slipped away from our reviews - we use normally always either one of the IDE plugins (eclipse, intellij, vs-code) to view reports or directly look into the JSON reports. So we were not aware of the problematic HTML report rendering or that somebody use those reports to handle false positives. Sorry!

This came up ~ 6 month ago while we introduced the call hierarchy into reports. 

### How to fix the wrong data?
- Wait for release sechub-server 0.26.0 (contains the bugfix)
- Download your false positive settings for your project as JSON file and store it at your local machine,
  see https://daimler.github.io/sechub/latest/sechub-client.html#getfalsepositives
- Use the sechub client with the downloaded file to remove all existing false positives
  https://daimler.github.io/sechub/latest/sechub-client.html#section-client-false-positives-unmark 
- After this, make a copy of the JSON file (e.g. call it `new-false-positives.json`) and review listed ones _(review process is explained in next chapter)_
- After review upload the `new-false-positives.json` by sechub client as explained at : 
  https://daimler.github.io/sechub/latest/sechub-client.html#section-client-false-positives-mark 
- you are done

###  How to review/update `new-false-positives.json` ?
- Open `new-false-positives.json` inside a text editor of your choice
- You will find something like this:

```json
{   
    "apiVersion": "1.0", 
    "type" : "falsePositiveJobDataList", 
    
    "jobData": [
            {
                "jobUUID": "ed8f9c17-7041-4375-a07e-2fe29c7c26e9",
                "findingId": 42, 
                "comment" : "an (optional) comment 1 from user who set this false positive"
            },
            {
                "jobUUID": "fe8f3c37-1332-2363-b06c-1gc13d3d31a2",
                "findingId": 6, 
                "comment" : "an (optional) comment 2 from user who set this false positive"
            }
      ]          
}
```
- each job data entry has a jobUUID. For each entry do following:
  - Download the report  for this uuid by sechub client (even HTML will work at this point when server-0.26.0 is running)
  -  check if the listed finding Id inside the job data is the wanted false positive inside the report  
   _(normally the comment  should help you where the user who marked the false positive has described why this was a false one)_
  - if the false-positive finding Id was correct set, keep it as is 
  - if the false-positive setting Id was incorrect, check for the correct finding id, change it inside the JSON 
- save the changed JSON file
- upload it by sechub-client (is described in chapter before)
