### ISSUE TITLE
Report and interactive falsePositive Code does not match

### ISSUE THREAD

**Issue by MichaBub** [Daimler/sechub#597]
Report and interactive falsePositive Code does not match
Report should have first occurence and not last of call stack on top
int that case id 0 on top instead of id 13

![image](https://user-images.githubusercontent.com/14907390/115412624-c5f21180-a1f4-11eb-9822-852884993d16.png)

**Comment by de-jcup** [comment]
I think this is the same bug which is fixed by #576  : Inside the HTML report "Id" is not the finding ids but the call step number (even this was the wrong one, because steps also start with 1 here).

Unfortunately this was slipped away from our reviews - we use normally always use one of the plugins (eclipse, intellij, vs-code) to view reports or directly look into the JSON reports. So we were not aware of the problematic report rendering. Sorry!

**Comment by de-jcup** [comment]
@MichaBub : Sorry about the late response!

**Comment by Jeeppler** [comment]
@MichaBub thanks for reporting this issue.
